### ISSUE TITLE
Must use SQLcl to install sales_history schema

### ISSUE THREAD

**Issue by RogerFord** [oracle-samples/db-sample-schemas#16]
README file suggests SQLcl or SQL*Plus can be used to load schemas. However the sales_history schema relies on the LOAD command which is only available in SQLcl. If you use SQL*Plus, the install appears to work, but the final verification step shows that several of the tables are empty.

**Comment by gvenzl** [comment]
The [README of the `sales_history` schema](https://github.com/oracle-samples/db-sample-schemas/tree/main/sales_history#schema-dependencies-and-requirements) states the requirement for SQLcl.

I do not see a reference where the README suggests that it can be installed via SQL\*PLus, could you please clarify?

**Comment by gvenzl** [comment]
Closing due to no response.
