### ISSUE TITLE
ORA-00600: internal error code, arguments: [kkpo_rcinfo_defstg:objnotfound]

### ISSUE THREAD

**Issue by Ketan-33** [oracle-samples/db-sample-schemas#25]
DECLARE
*
ERROR at line 1:
ORA-00600: internal error code, arguments: [kkpo_rcinfo_defstg:objnotfound],
[62781], [], [], [], [], [], [], [], [], [], []
ORA-06512: at line 12
ORA-06512: at line 5

**Comment by gvenzl** [comment]
Hi @Ketan-33,

It appears you have encountered an Oracle Database internal error.
This repository's focus is on the freely provided Sample Schemas and their associated scripts.

Please file a Service Request with Oracle Support or seek further help on forums.oracle.com

Thanks,
