### ISSUE TITLE
[Solved] ORA-65096: common user or role name must start with prefix C##

### ISSUE THREAD

**Issue by youssefifkiren** [oracle-samples/db-sample-schemas#27]
```sql
CREATE USER hr IDENTIFIED BY "*****"
*
ERROR at line 1:
ORA-65096: common user or role name must start with prefix C##
```
Oracle Database 23ai Free Release 23.0.0.0.0 - Develop, Learn, and Run for Free
Version 23.5.0.24.07

**Comment by rolandm** [comment]
You are logged in to the root container in a multitenant dB instance. Please detect the pdbs by command 'show pdbs ' and change to the pdb (=pluggable database) you want to use. In example setups this pdb has a name like XEPDB1 or similar.
